Repository KEA-5th-Myaong/blog-service, pull requests merged in 2024-12, with the labels that each got.

#23 :recycle: [#21] refactor: Tuple → SortedEntity<>
  src/main/java/myaong/popolog/blogservice/converter/MainPageConverter.java
  src/main/java/myaong/popolog/blogservice/repository/QPostRepository.java
  src/main/java/myaong/popolog/blogservice/repository/QPostRepositoryImpl.java
  src/main/java/myaong/popolog/blogservice/service/MainPageServiceImpl.java
Labels: :recycle: Refactor

#27 Feat/#24-blog-cud/kan-254
  src/main/java/myaong/popolog/blogservice/common/Prefix.java
  src/main/java/myaong/popolog/blogservice/controller/PostsController.java
  src/main/java/myaong/popolog/blogservice/dto/request/PostCreateRequest.java
  src/main/java/myaong/popolog/blogservice/dto/request/PostUpdateRequest.java
  src/main/java/myaong/popolog/blogservice/dto/response/PostCreateResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/PostDetailResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/PostPicResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/PostsResponse.java
  src/main/java/myaong/popolog/blogservice/entity/Post.java
  src/main/java/myaong/popolog/blogservice/repository/BookmarkRepository.java
  src/main/java/myaong/popolog/blogservice/repository/CommentRepository.java
  src/main/java/myaong/popolog/blogservice/repository/LikeRepository.java
  src/main/java/myaong/popolog/blogservice/repository/PostRepository.java
  src/main/java/myaong/popolog/blogservice/service/PostsService.java
  src/main/java/myaong/popolog/blogservice/service/PostsServiceImpl.java
Labels: :recycle: Refactor, :sparkles: Feature

#31 fix/#30-main-page-response-type
  src/main/java/myaong/popolog/blogservice/converter/MainPageConverter.java
  src/main/java/myaong/popolog/blogservice/dto/response/MainPageResponse.java
  src/main/java/myaong/popolog/blogservice/repository/LikeRepository.java
Labels: :hammer: Fix

#29 Feat/#28-bookmark-and-report/kan-265
  build.gradle
  src/main/java/myaong/popolog/blogservice/controller/PostsController.java
  src/main/java/myaong/popolog/blogservice/controller/ProfileController.java
  src/main/java/myaong/popolog/blogservice/dto/request/PostCreateRequest.java
  src/main/java/myaong/popolog/blogservice/dto/request/PostUpdateRequest.java
  src/main/java/myaong/popolog/blogservice/dto/request/ReportRequest.java
  src/main/java/myaong/popolog/blogservice/dto/request/UpdateProfileRequest.java
  src/main/java/myaong/popolog/blogservice/dto/response/PostBookmarkResponse.java
  src/main/java/myaong/popolog/blogservice/repository/BookmarkRepository.java
  src/main/java/myaong/popolog/blogservice/repository/PostRepository.java
  src/main/java/myaong/popolog/blogservice/repository/ReportRepository.java
  src/main/java/myaong/popolog/blogservice/service/PostsService.java
  src/main/java/myaong/popolog/blogservice/service/PostsServiceImpl.java
  src/main/java/myaong/popolog/blogservice/service/ProfileCommandServiceImpl.java
  src/main/java/myaong/popolog/blogservice/service/S3ApiService.java
Labels: :recycle: Refactor, :sparkles: Feature

#35 Fix/#34 valid post title profile/kan 279
  src/main/java/myaong/popolog/blogservice/common/exception/ApiCode.java
  src/main/java/myaong/popolog/blogservice/entity/Post.java
  src/main/java/myaong/popolog/blogservice/repository/PostRepository.java
  src/main/java/myaong/popolog/blogservice/service/PostsServiceImpl.java
Labels: :hammer: Fix

#36 Feature/#26 post searching/kan 264
  src/main/java/myaong/popolog/blogservice/controller/BlogController.java
  src/main/java/myaong/popolog/blogservice/repository/QPostRepository.java
  src/main/java/myaong/popolog/blogservice/repository/QPostRepositoryImpl.java
  src/main/java/myaong/popolog/blogservice/service/MainPageService.java
  src/main/java/myaong/popolog/blogservice/service/MainPageServiceImpl.java
Labels: :sparkles: Feature

#38 :sparkles: [#37] feature: 블로그 관심 직군 동기화 API 구현 - 서비스 간 API line 8
  src/main/java/myaong/popolog/blogservice/controller/ProfileController.java
  src/main/java/myaong/popolog/blogservice/dto/request/PrejobsRequest.java
  src/main/java/myaong/popolog/blogservice/repository/PrejobRepository.java
  src/main/java/myaong/popolog/blogservice/service/ProfileCommandService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileCommandServiceImpl.java
Labels: :sparkles: Feature
