Repository KEA-5th-Myaong/blog-service, pull requests merged in 2024-11, with the labels that each got.

#11 Fix/#10 entity mapping/kan 188
  src/main/java/myaong/popolog/blogservice/common/exception/ApiCode.java
  src/main/java/myaong/popolog/blogservice/config/SwaggerConfig.java
  src/main/java/myaong/popolog/blogservice/controller/ProfileController.java
  src/main/java/myaong/popolog/blogservice/converter/ProfileConverter.java
  src/main/java/myaong/popolog/blogservice/dto/request/ProfileRequest.java
  src/main/java/myaong/popolog/blogservice/dto/response/CommentResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/PostDetailResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/ProfileResponse.java
  src/main/java/myaong/popolog/blogservice/entity/BaseEntity.java
  src/main/java/myaong/popolog/blogservice/entity/Comment.java
  src/main/java/myaong/popolog/blogservice/entity/Follow.java
  src/main/java/myaong/popolog/blogservice/entity/MemberPrejob.java
  src/main/java/myaong/popolog/blogservice/entity/MemberProfile.java
  src/main/java/myaong/popolog/blogservice/entity/Post.java
  src/main/java/myaong/popolog/blogservice/entity/Profile.java
  src/main/java/myaong/popolog/blogservice/repository/FollowRepository.java
  src/main/java/myaong/popolog/blogservice/repository/MemberPrejobRepository.java
  src/main/java/myaong/popolog/blogservice/repository/MemberProfileRepository.java
  src/main/java/myaong/popolog/blogservice/repository/ProfileRepository.java
  src/main/java/myaong/popolog/blogservice/service/BlogService.java
  src/main/java/myaong/popolog/blogservice/service/PostsService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileCommandService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileCommandServiceImpl.java
  src/main/java/myaong/popolog/blogservice/service/ProfileQueryService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileQueryServiceImpl.java
Labels: :hammer: Fix

#13 Feat/#12 main page/kan 199
  .gitignore
  build.gradle
  src/main/java/myaong/popolog/blogservice/common/exception/ApiCode.java
  src/main/java/myaong/popolog/blogservice/common/exception/GlobalExceptionHandler.java
  src/main/java/myaong/popolog/blogservice/config/QueryDSLConfig.java
  src/main/java/myaong/popolog/blogservice/controller/BlogController.java
  src/main/java/myaong/popolog/blogservice/controller/PostsController.java
  src/main/java/myaong/popolog/blogservice/converter/MainPageConverter.java
  src/main/java/myaong/popolog/blogservice/dto/response/MainPageResponse.java
  src/main/java/myaong/popolog/blogservice/entity/Bookmark.java
  src/main/java/myaong/popolog/blogservice/entity/Prejob.java
  src/main/java/myaong/popolog/blogservice/entity/Profile.java
  src/main/java/myaong/popolog/blogservice/entity/Report.java
  src/main/java/myaong/popolog/blogservice/repository/BookmarkRepository.java
  src/main/java/myaong/popolog/blogservice/repository/CommentRepository.java
  src/main/java/myaong/popolog/blogservice/repository/LikeRepository.java
  src/main/java/myaong/popolog/blogservice/repository/PostRepository.java
  src/main/java/myaong/popolog/blogservice/repository/PrejobRepository.java
  src/main/java/myaong/popolog/blogservice/repository/ProfileRepository.java
  src/main/java/myaong/popolog/blogservice/repository/QPostRepository.java
  src/main/java/myaong/popolog/blogservice/repository/QPostRepositoryImpl.java
  src/main/java/myaong/popolog/blogservice/repository/ReportRepository.java
  src/main/java/myaong/popolog/blogservice/service/BlogService.java
  src/main/java/myaong/popolog/blogservice/service/BookmarkService.java
  src/main/java/myaong/popolog/blogservice/service/MainPageService.java
  src/main/java/myaong/popolog/blogservice/service/MainPageServiceImpl.java
  src/main/java/myaong/popolog/blogservice/service/PostsService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileQueryService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileQueryServiceImpl.java
Labels: :sparkles: Feature

#16 Feature/#14 manage profile/kan 238
  .gitignore
  build.gradle
  src/main/java/myaong/popolog/blogservice/BlogServiceApplication.java
  src/main/java/myaong/popolog/blogservice/common/Prefix.java
  src/main/java/myaong/popolog/blogservice/common/exception/ApiCode.java
  src/main/java/myaong/popolog/blogservice/common/exception/GlobalExceptionHandler.java
  src/main/java/myaong/popolog/blogservice/config/S3Config.java
  src/main/java/myaong/popolog/blogservice/config/SwaggerConfig.java
  src/main/java/myaong/popolog/blogservice/controller/ProfileController.java
  src/main/java/myaong/popolog/blogservice/converter/ProfileConverter.java
  src/main/java/myaong/popolog/blogservice/dto/request/NewProfileRequest.java
  src/main/java/myaong/popolog/blogservice/dto/request/ProfileRequest.java
  src/main/java/myaong/popolog/blogservice/dto/request/UpdateProfileRequest.java
  src/main/java/myaong/popolog/blogservice/dto/response/ProfileInfoResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/ProfilePicUrlResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/ProfileResponse.java
  src/main/java/myaong/popolog/blogservice/entity/Profile.java
  src/main/java/myaong/popolog/blogservice/repository/ProfileRepository.java
  src/main/java/myaong/popolog/blogservice/service/FollowQueryService.java
  src/main/java/myaong/popolog/blogservice/service/FollowQueryServiceImpl.java
  src/main/java/myaong/popolog/blogservice/service/MainPageServiceImpl.java
  src/main/java/myaong/popolog/blogservice/service/ProfileCommandService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileCommandServiceImpl.java
  src/main/java/myaong/popolog/blogservice/service/ProfileQueryService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileQueryServiceImpl.java
  src/main/java/myaong/popolog/blogservice/service/S3ApiService.java
  src/main/resources/bootstrap.yml
Labels: :sparkles: Feature

#18 Feature/#17 follow/kan 239
  src/main/java/myaong/popolog/blogservice/controller/ProfileController.java
  src/main/java/myaong/popolog/blogservice/converter/ProfileConverter.java
  src/main/java/myaong/popolog/blogservice/dto/SortedEntity.java
  src/main/java/myaong/popolog/blogservice/dto/response/FollowProfileDTO.java
  src/main/java/myaong/popolog/blogservice/dto/response/FollowResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/FollowersResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/FollowingsResponse.java
  src/main/java/myaong/popolog/blogservice/repository/ProfileRepository.java
  src/main/java/myaong/popolog/blogservice/repository/QProfileRepository.java
  src/main/java/myaong/popolog/blogservice/repository/QProfileRepositoryImpl.java
  src/main/java/myaong/popolog/blogservice/service/ProfileCommandService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileCommandServiceImpl.java
  src/main/java/myaong/popolog/blogservice/service/ProfileQueryService.java
  src/main/java/myaong/popolog/blogservice/service/ProfileQueryServiceImpl.java
Labels: :hammer: Fix, :recycle: Refactor, :sparkles: Feature

#19 Feature/#15 notification send/kan 240
  build.gradle
  src/main/java/myaong/popolog/blogservice/BlogServiceApplication.java
  src/main/java/myaong/popolog/blogservice/controller/CommentController.java
  src/main/java/myaong/popolog/blogservice/controller/PostsController.java
  src/main/java/myaong/popolog/blogservice/dto/request/CommentPostRequest.java
  src/main/java/myaong/popolog/blogservice/dto/request/CommentUpdateRequest.java
  src/main/java/myaong/popolog/blogservice/dto/request/ReplyRequest.java
  src/main/java/myaong/popolog/blogservice/dto/response/CommentPostResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/CommentUpdateResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/LikeResponse.java
  src/main/java/myaong/popolog/blogservice/dto/response/ReplyResponse.java
  src/main/java/myaong/popolog/blogservice/entity/Comment.java
  src/main/java/myaong/popolog/blogservice/feign/client/NotificationServiceFeignClient.java
  src/main/java/myaong/popolog/blogservice/feign/constant/NotificationType.java
  src/main/java/myaong/popolog/blogservice/feign/dto/request/NotificationRequest.java
  src/main/java/myaong/popolog/blogservice/feign/service/NotificationFeignService.java
  src/main/java/myaong/popolog/blogservice/repository/LikeRepository.java
  src/main/java/myaong/popolog/blogservice/service/CommentService.java
  src/main/java/myaong/popolog/blogservice/service/PostsService.java
Labels: :hammer: Fix, :recycle: Refactor, :sparkles: Feature
